name: Build Assimp CLI

on:
  schedule:
    - cron: '0 0 * * 3' # Every wednesday at midnight
  workflow_dispatch: # On demand

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: macos-latest
        os: [windows-latest]

    steps:
    - name: Clone Assimp
      uses: actions/checkout@v4
      with:
        repository: assimp/assimp
        ref: master
        submodules: true

    - name: Configure CMake
      run: cmake -S . -B ./build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_ASSIMP_VIEW=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_INSTALL=OFF -DASSIMP_INSTALL_PDB=OFF

    - name: List build dir.
      run: dir ./build

    - name: Build w/ CMake
      run: cmake --build ./build --config Release

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        # TODO: Append current date to
        name: assimp-cli-${{ matrix.os }}
        path: build/bin
