name: Build Assimp CLI

on:
  schedule:
    - cron: '0 0 * * 3' # Every wednesday at midnight
  workflow_dispatch: # On demand

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: macos-latest
        os: [windows-latest]

    steps:
    - name: Get Current Date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: YYYY-MM-DD

    - name: Clone Assimp
      uses: actions/checkout@v4
      with:
        path: assimp
        repository: assimp/assimp
        ref: master
        submodules: true

    - name: Configure Build
      run: cmake -S ./assimp -B ./assimp/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_ASSIMP_VIEW=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_INSTALL=OFF -DASSIMP_INSTALL_PDB=OFF

    - name: Build Release
      run: cmake --build ./assimp/build --config Release

    - name: Back To My Repo
      uses: actions/checkout@v4
      with:
        path: weekly

    - name: Create Tag
      run: git tag ${{ steps.date.outputs.time }} && git push origin --tags
      working-directory: ./weekly

    - name: Release Tag
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: ./assimp/build/bin/Release/assimp*
        tag_name: ${{ steps.date.outputs.time }}
