name: Build Assimp CLI

on:
  push:
    tags:
      - '*'
  workflow_dispatch: # On demand.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            os_and_arch: windows-x64
            archive_type: zip
            archive_ext: zip
          - os: macos-latest
            os_and_arch: macos-universal2
            archive_type: tar
            archive_ext: 'tar.gz'

    steps:
    - name: Get Current Date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: YYYY-MM-DD

    - name: Clone Assimp
      uses: actions/checkout@v4
      with:
        repository: assimp/assimp
        ref: master
        submodules: true

    - name: Configure Build
      if: matrix.os == 'windows-latest'
      run: cmake -S . -B ./build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_ASSIMP_VIEW=OFF -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_INSTALL=OFF -DASSIMP_INSTALL_PDB=OFF

    - name: Configure Build
      if: matrix.os == 'macos-latest'
      run: cmake -S . -B ./build -G "Unix Makefiles" -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_ASSIMP_TOOLS=ON -DASSIMP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DASSIMP_INSTALL=OFF -DASSIMP_INSTALL_PDB=OFF

    - name: Build Release
      run: cmake --build ./build --config Release

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        path: build/bin
        type: ${{ matrix.archive_type }}
        filename: assimp-cli-${{ steps.date.outputs.time }}-${{ matrix.os_and_arch }}.${{ matrix.archive_ext }}

    - name: Release With Tag
      uses: softprops/action-gh-release@v1
      with:
        body: This is an automatic build of the Assimp CLI tool.
        files: assimp-cli-${{ steps.date.outputs.time }}-${{ matrix.os_and_arch }}.${{ matrix.archive_ext }}
        tag_name: ${{ steps.date.outputs.time }} # This tag has just been created by the "Tag With Date" action.
